import { writeFileSync } from 'node:fs';

const url = (process.env.SUPABASE_URL || '').trim();
const key = (process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY || '').trim();

// Render, Vercel, Netlify and most CI systems set one of these. If we're
// building on a hosted platform and the Supabase env vars are missing, fail
// loudly instead of silently shipping a site with no backend.
const onHostedPlatform = Boolean(
  process.env.RENDER || process.env.VERCEL || process.env.NETLIFY || process.env.CI
);

if (onHostedPlatform && (!url || !key)) {
  console.error(
    "[Elite Ballers] Missing SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY.\n" +
    "  Set both in your host's Environment Variables (Render: Dashboard -> your " +
    "Static Site -> Environment) and redeploy."
  );
  process.exit(1);
}

if (url && key) {
  writeFileSync(
    'js/config.js',
    `// Generated by scripts/build-config.mjs from SUPABASE_URL / SUPABASE_PUBLISHABLE_KEY.\n` +
    `window.EB_SUPABASE_CONFIG = ${JSON.stringify({ url, publishableKey: key })};\n`
  );
  console.log('[Elite Ballers] Generated browser-safe Supabase config from environment variables.');
} else {
  console.warn(
    '[Elite Ballers] No SUPABASE_URL/SUPABASE_PUBLISHABLE_KEY in the environment - ' +
    'leaving js/config.js untouched for local development.'
  );
}
